<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://blogs.msdn.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx</link><description>In the February 2014 HCK for Windows 8.1 QFE, these changes are made to the System – Sleep and PNP (disable and enable) with IO Before and After test: You no longer need to configure all devices on the system before the test can run. - We also released</description><dc:language>en-US</dc:language><generator>Telligent Evolution Platform Developer Build (Build: 5.6.50428.7875)</generator><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10502018</link><pubDate>Fri, 21 Feb 2014 06:19:59 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10502018</guid><dc:creator>HC Huang</dc:creator><description>&lt;p&gt;Hi Sir,&lt;/p&gt;
&lt;p&gt;I filed a bug on dashboard about this test.&lt;/p&gt;
&lt;p&gt;Could you help to take a look at the failure&amp;#39;s hckx file?&lt;/p&gt;
&lt;p&gt;Bug ID is 605896.&lt;/p&gt;
&lt;p&gt;Thank you in advance.&lt;/p&gt;
&lt;p&gt;HC&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10502018" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10501217</link><pubDate>Tue, 18 Feb 2014 19:59:15 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10501217</guid><dc:creator>KAENNGAI CHAN</dc:creator><description>&lt;p&gt;with IO Before and After test: You no longer need to configure all devices on the system before the test can run. - We also released...&lt;/p&gt;
&lt;p&gt;i like how Microsoft use the words and i know i will fail on test without test, let people have more talents have more chance for test&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10501217" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10501160</link><pubDate>Tue, 18 Feb 2014 16:50:54 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10501160</guid><dc:creator>paul_Reed55</dc:creator><description>&lt;p&gt;Hi Mike Lu,&lt;/p&gt;
&lt;p&gt;When the requirement relaxations were finalized, we were approaching the holiday season in December and many teams were leaving for extended holiday. &amp;nbsp;Then when they returned there was a really tight deadline to make the February HCK QFE release. &amp;nbsp;Not all teams were able to do so. &amp;nbsp;However, we have published errata filters that will turn all failures into pass. &amp;nbsp;So if you do not wish to test for the quality bar, you can run the test and it will fail. &amp;nbsp;The errata will convert it to a pass. &amp;nbsp;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10501160" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10500690</link><pubDate>Mon, 17 Feb 2014 07:11:26 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10500690</guid><dc:creator>Summer Nie</dc:creator><description>&lt;p&gt;Hi, Mark:&lt;/p&gt;
&lt;p&gt;Is Mutt device supposed to be plugged in during &amp;quot;device status check&amp;quot;? &lt;/p&gt;
&lt;p&gt;As we are running QFE006, and it still failed on Super MUTT during device status check phase, so the main test will not process at all. &lt;/p&gt;
&lt;p&gt;Per the description, does it mean we could unplug the Super Mutt device from system once device status check was passing? &amp;nbsp; &lt;/p&gt;
&lt;p&gt;Thank you!&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10500690" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10499097</link><pubDate>Thu, 13 Feb 2014 03:37:25 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10499097</guid><dc:creator>Mike Lu</dc:creator><description>&lt;p&gt;Are Fidelity Test and Firmware Post Time test supposed to be moved to the optional test?&lt;/p&gt;
&lt;p&gt;Why do I still find them as certification level in this QFE update?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10499097" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10498965</link><pubDate>Wed, 12 Feb 2014 18:29:35 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10498965</guid><dc:creator>Mark Hughes</dc:creator><description>&lt;p&gt;Hi Mike,&lt;/p&gt;
&lt;p&gt;Some Sysdev (Dashboard) accounts are set up with bug management services that allows bugs to be filed directly through the Sysdev site. &amp;nbsp; If your Sysdev account is not set up with bug management the only way to report a HCK issues is through the CSS team. &lt;/p&gt;
&lt;p&gt;BTW....Your account is set up with the bug management feature. &amp;nbsp; &amp;nbsp;&lt;/p&gt;
&lt;p&gt;Thanks,&lt;/p&gt;
&lt;p&gt;Mark&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10498965" width="1" height="1"&gt;</description></item><item><title>re: Changes to “System - Sleep and PNP (disable and enable) with IO Before and After (Certification)” test in February HCK QFE</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/02/11/changes-to-system-sleep-and-pnp-disable-and-enable-with-io-before-and-after-certification-test-in-february-hck-qfe.aspx#10498705</link><pubDate>Wed, 12 Feb 2014 02:58:02 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10498705</guid><dc:creator>Mike Cao</dc:creator><description>&lt;p&gt;Referring to your words &amp;quot;We recommend that you run the test with QFE 006 changes and report any test or operating system bugs to us &amp;quot; ,How Can I contact with Microsoft without CSS support ?&lt;/p&gt;
&lt;p&gt;Thanks,&lt;/p&gt;
&lt;p&gt;Mike&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10498705" width="1" height="1"&gt;</description></item></channel></rss>