<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://blogs.msdn.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx</link><description>We've updated all active errata filters for the Windows Hardware Certification Kit (HCK).&amp;#160; All active errata that weren't fixed in the test kit are now extended until 12/31/2014. We'll reevaluate all active errata again about 3 months before the</description><dc:language>en-US</dc:language><generator>Telligent Evolution Platform Developer Build (Build: 5.6.50428.7875)</generator><item><title>re: Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx#10504166</link><pubDate>Fri, 28 Feb 2014 22:34:00 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10504166</guid><dc:creator>Ludi</dc:creator><description>&lt;p&gt;For how long are Windows Hardware Certifications good for? And where can I find that info?&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10504166" width="1" height="1"&gt;</description></item><item><title>re: Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx#10487369</link><pubDate>Mon, 06 Jan 2014 19:50:35 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10487369</guid><dc:creator>paul_Reed55</dc:creator><description>&lt;p&gt;Hi Mike,&lt;/p&gt;
&lt;p&gt;Not all manual errata are posted to the website I listed above as some errata may be for particular situations. &amp;nbsp;If you have a question about a specific errata, please go a head and list the errata ID here or contact us directly at logofb@microsoft.com and we will get you a response. &amp;nbsp;&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10487369" width="1" height="1"&gt;</description></item><item><title>re: Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx#10483117</link><pubDate>Wed, 18 Dec 2013 05:58:00 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10483117</guid><dc:creator>Mike Cao</dc:creator><description>&lt;p&gt;How about Manual Erratas ?&lt;/p&gt;
&lt;p&gt;Thanks,&lt;/p&gt;
&lt;p&gt;Mike&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10483117" width="1" height="1"&gt;</description></item><item><title>re: Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx#10481702</link><pubDate>Thu, 12 Dec 2013 23:22:24 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10481702</guid><dc:creator>paul_Reed55</dc:creator><description>&lt;p&gt;HI Stanley,&lt;/p&gt;
&lt;p&gt;We publish a list of all automated errata and its expiration date off of the Sysdev website.&lt;/p&gt;
&lt;p&gt;&lt;a rel="nofollow" target="_new" href="https://sysdev.microsoft.com/en-US/Hardware/ec/"&gt;sysdev.microsoft.com/.../ec&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Filters and the website are updated after 6pm on a daily basis.&lt;/p&gt;
&lt;p&gt;As for contingencies. &amp;nbsp;Contingencies are an agreement to fix an issue. &amp;nbsp;If an issue needs to be discussed, it is best to get in touch with your Microsoft contact that you work with on the contingency and discuss the status of your issue.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10481702" width="1" height="1"&gt;</description></item><item><title>re: Errata expiration guidelines</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2013/12/10/errata-expiration-guidelines.aspx#10481289</link><pubDate>Wed, 11 Dec 2013 19:04:53 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10481289</guid><dc:creator>Stanley Jackson</dc:creator><description>&lt;p&gt;We need to see the completed detail list of what was extended and what was not. &amp;nbsp; &amp;nbsp; &amp;nbsp;Next &amp;nbsp; what is plan to address contingency and manual errata&amp;#39;s it&amp;#39;s clear MS is not able o resolve many issues and the OEMs may need additional time as well. &amp;nbsp; &amp;nbsp; &lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10481289" width="1" height="1"&gt;</description></item></channel></rss>