<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://blogs.msdn.com/utility/FeedStylesheets/rss.xsl" media="screen"?><rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:wfw="http://wellformedweb.org/CommentAPI/"><channel><title>Self-test submission model for touch device and precision touchpad certification</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/01/23/self-test-submission-model-for-touch-device-and-precision-touchpad-certification.aspx</link><description>On January 1, 2014, the touch device and precision touchpad (PTP) certification program enabled a self-test submission model. Partners can now submit touch devices and precision touchpads for certification without sending hardware to WTTL/WPTL for full</description><dc:language>en-US</dc:language><generator>Telligent Evolution Platform Developer Build (Build: 5.6.50428.7875)</generator><item><title>re: Self-test submission model for touch device and precision touchpad certification</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/01/23/self-test-submission-model-for-touch-device-and-precision-touchpad-certification.aspx#10506463</link><pubDate>Mon, 10 Mar 2014 06:58:32 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10506463</guid><dc:creator>Tina</dc:creator><description>&lt;p&gt;From &lt;a rel="nofollow" target="_new" href="http://msdn.microsoft.com/en-us/library/windows/hardware/dn456917.aspx"&gt;msdn.microsoft.com/.../dn456917.aspx&lt;/a&gt;,&lt;/p&gt;
&lt;p&gt;PT3 need to use 7mm diameter contacts; however, there is no mention of the same required for RA.&lt;/p&gt;
&lt;p&gt;May I know does RA need to use 7mm diameter contacts, too?&lt;/p&gt;
&lt;p&gt;Thanks.&lt;/p&gt;
&lt;p&gt;Tina&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10506463" width="1" height="1"&gt;</description></item><item><title>re: Self-test submission model for touch device and precision touchpad certification</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/01/23/self-test-submission-model-for-touch-device-and-precision-touchpad-certification.aspx#10504806</link><pubDate>Mon, 03 Mar 2014 23:40:34 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10504806</guid><dc:creator>Andy_Wen</dc:creator><description>&lt;p&gt;Hello,&lt;/p&gt;
&lt;p&gt;As long as the device can pass requirements, it&amp;#39;d be eligible for self-test submission.&lt;/p&gt;
&lt;p&gt;Thanks,&lt;/p&gt;
&lt;p&gt;Andy&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10504806" width="1" height="1"&gt;</description></item><item><title>re: Self-test submission model for touch device and precision touchpad certification</title><link>http://blogs.msdn.com/b/windows_hardware_certification/archive/2014/01/23/self-test-submission-model-for-touch-device-and-precision-touchpad-certification.aspx#10502866</link><pubDate>Tue, 25 Feb 2014 07:37:00 GMT</pubDate><guid isPermaLink="false">91d46819-8472-40ad-a661-2c78acb4018c:10502866</guid><dc:creator>TY</dc:creator><description>&lt;p&gt;Hi, &lt;/p&gt;
&lt;p&gt;I wonder if there is any criteria for proceeding self-test submission or full-test submission? &lt;/p&gt;
&lt;p&gt;Thanks.&lt;/p&gt;
&lt;p&gt;TY.&lt;/p&gt;
&lt;div style="clear:both;"&gt;&lt;/div&gt;&lt;img src="http://blogs.msdn.com/aggbug.aspx?PostID=10502866" width="1" height="1"&gt;</description></item></channel></rss>